# port config
server:
  port: 8008

# datasource config
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@oracle.team-greedy.com:1521:xe
    username: C##SPRING
    password: SPRING

# mybatis config
mybatis:
  mapper-locations: mappers/**.xml